_sass/molecules/_alert.scss
Even though `.info-alert` is mentioned in the style guide, it's not
defined in the stylesheets. I need a very basic alert component to
convey information about a page, for example, 'This page describes a
past project'. This commit adds a basic `.info-alert` component that
extends `.alert` and removes the bottom border.
We need to revisit the `.alert` component styling more holistically, but
for now I just want to use the lightest touch to add something very
basic.
=> Add .info-alert component styling

_sass/organisms/_hero.scss
I'm adding the ability to specify a background image for header hero elements on the Code for
America website. This commit set some default properties for handling background images in hero
elements. Specifically, it makes the background image cover the hero element, and it positions the
background image 'center center'.
=> Set background-size and background-position for hero elements

_sass/templates/_primary-page.scss
Some primary pages will now have a header background image. This commit updates the alert
background color on primary pages so that, instead of being dark blue, they're now black and very
transparent. On most pages that have blue headers, the end results will look the same as it did
before.
=> Change global alert background color on primary pages

_sass/molecules/_slab.scss
The stylesheet currently includes a blue background slab. A slight variation on the blue style would
be useful -- for example, the Summit 2018 branding uses medium blue and dark blue blocks next to
eachother. This commit updates `.blue-bg-slab` to use `$color-blue` instead of `$dark-blue`, and adds a `.dark-blue-bg-slab` variant that uses `$color-dark-blue` for its background-color.
This commit adds a dark blue slab style.
=> Add dark blue slab style

_sass/atoms/_typography.scss, _sass/organisms/_global-header.scss, _sass/templates/_home.scss
Make sure that reverse-header text is white. This includes removing aggressive properties to make headings black, to instead allow headings to inherit their color from their parent elements.
=> Make reverse-header text white

.travis.yml
Since the main codeforamerica.org site hotlinks our style guide without
versioning, in order to make backwards incompatible changes on master,
we are creating a new branch "cfa-dot-org" that will remain
backwards-compatible with the existing styles until the
codeforamerica/cms repo can be modified to use the versioned npm build.
=> Only auto-deploy "cfa-dot-org" branch

_sass/main.scss, _sass/templates/_campaign-page.scss
A fundraising campaign is starting tomorrow and there was a request from the development team to
set up a campaign donation page. This adds a campaign-page template to our style-guide. This is a
quick, messy addition and will need to be revisited.
=> Add a quick new campaign-page template

_sass/molecules/_slab.scss
Craft supports creating an element with this class, but there was never
any implementation of the style.
=> Add `red-bg-slab` variant

_sass/organisms/_hero.scss, package.json
When importing these files separately, using a default-level variable
here will allow style guide users to change the hero color like so:
```sass
@import '~@codeforamerica/style/_sass/core/_variables.scss';
$hero-color: $color-red;
@import '~@codeforamerica/style/_sass/main.scss';
```
=> Add $hero-color variable for customization

_atoms/buttons_and_forms.md, _sass/atoms/_input.scss, package.json
@fritzjooste and I are working on improving styling in the PITJB, and
realized that `<label>`s are a hot mess.
We shouldn't be using them as headings, and the style guide should
feature their use attached to form inputs.
This commit cleans that up a bit and makes them normal weight.
=>  Improve <label> styling and display in style guide

CHANGELOG.md, _sass/organisms/_mobile-navigation.scss, package.json
Since the user can customize `$hero-color`, allowing customizable mobile
nav background color is necessary to prevent jarring transitions.
=>  Add `$mobile-nav-background-color` to allow customization

CHANGELOG.md, _sass/molecules/_card.scss
This is a retry of #20 which I accidentally merged.
There are many reasons to not assume that an entire card is a link: if
you don't want the whole card to be a link, if you want to have multiple
links inside the card, and just in general if you want to use a card for
a non-linking purpose.
By removing the from these selectors we can make the cards more
versatile.
=> Remove anchor tag selector from card styles

_sass/molecules/_card.scss
This is useful for displaying cards that have visual contrast against a
grey background. For example, this will be used on brigade profile
pages, and could be used on the job board featured jobs section.
Use it like:
`<div class="card card--white link-card">`
=> Add "card--white" variant

CHANGELOG.md, _sass/molecules/_message.scss, _sass/organisms/_global-header.scss, package.json
This will improve spacing, especially in the case of two messages
adjacent to each other.
E.g.
See: codeforamerica/brigade#568
=> Add margin-bottom to message component

_molecules/slabs.md, _sass/molecules/_slab.scss
The styleguide has styling for the `.border-top-slab` slab variant, but not for `.border-bottom-slab`, even though it's already set up in the CMS. This adds the same basic styling for the bottom-border slab.
I don't think the way that slabs (and other layout components) are styled/set up at the moment is optimal, and we're going to move to some better patterns very soon. This is intended as an interim fix.
=> Add styling for border-bottom-slab

_sass/organisms/_hero.scss
I'm adding a 'jumbo' variant of the hero component to be used in a new 'major events' template, for events like Summit. It has a bit of drama: it takes up most most (80%) of the vertical space of the screen and its content is displayed in its center.
This also add some styling of the sub-components of `hero--jumbo`, and starts including some BEM class names for the parts of the `slab` component, as we move towards BEM classic as a naming convention.
=> Add a jumbo variant of the hero component

_sass/core/_grid.scss
In a 12 column grid, it's now pretty standard for the column classes to follow a naming convention that looks something like `col-3`, `col-6` etc. I want to introduce a bit more flexibility with the placement of components into grids in the CMS, and having the column class names in this more-standard format will make it easier to do so.
=> Add column class names that start with 'col' followed by integer

_sass/molecules/_card.scss
We're moving towards BEM classic and, as I'm modifying templates and building new ones, I'm adding BEM-style class names to some of our existing components and subcomponents.
Some of the card variants still need to be BEM-ified in the future, like link-cards and supporters-cards etc.
=> Add some BEM class names for standard card subcomponents

_sass/core/_grid.scss
I'm adding a `content-grid-row` component to the codeforamerica.org CMS and this adds some styling, harnessing flexbox, to help align the sub-elements and make sure they're all the same height (on wider screens).
=> Add a 'grid-row' layout component

_sass/main.scss, _sass/molecules/_banner.scss
GivingTuesday is approaching and we want to add a prominent banner to the top of certain pages on the codeforamerica.org that includes an image that takes up half of the screen, along with a headline, some text, a call-to-action link and optionally some overhead text. This is a first stab at adding such a component.
=> Add banner component

_sass/core/_grid.scss, _sass/molecules/_card.scss
Previously all elements in a grid-row column would size up to the full height of the column, but there are some situations where I want to stack two sub-elements in one column element and the alignment was getting a bit screwy. This fixes those alignment issues, and makes cards take up the full height of the row, so I can still do rows of cards that all the same height.
=> Make the grid sizing of the grid row sub-element less agressive

_sass/atoms/_stat.scss
With the larger font-size and the added letter-spacing, some longer labels were looking too bloated. Let's remove these properties to make them more compact.
=> Make stat labels more compact

_sass/atoms/_blockquote.scss
We mostly use red for interactive elements, so I'm making quotes dark blue.
=> Make blockquotes dark blue, instead of red

_sass/atoms/_blockquote.scss
The open quotes image isn't rendering in production. This adds the full URL for the image file, to make sure the image renders. This isn't an ideal implementation, but rather a quick fix. Ideally I'd like the quotes to be done using text only, and once we've updated the website fonts to Proxima Nova (for consistency with our other marketing materials), I'll change this out.
=> Use full URL for open-quotes image

_sass/core/_variables.scss
A common pattern on codeforamerica.org is to alternate white-bg and gray-bg slabs, but the contrast between the two backgrounds is quite low and one some devices (esp. on mobile) one might not even notice the variation in background colors. This darkens the gray-shade variable, used in gray-background-slabs, to the same shade that is used in the global footer.
=> Darken gray shade to increase contrast between slabs

_sass/molecules/_slab.scss
The Summit branding makes use of a very dark shade of blue that we want to use on the Summit website. This adds a darkest-blue variant of the slab component, that uses that blue as a background color.
=> Add darkest-blue slab variant

_sass/molecules/_logos.scss
Logos (like the press logos on the codeforamerica.org homepage) aren't vertically centered next to eachother. This adds some flexbox properties to make sure they line up neatly.
=> Use flexbox to vertically align logos

_sass/molecules/_slab.scss
It's now possible in the codeforamerica.org CMS to specify a background image for content block 'slabs'. This adds some background size and position properties to slabs.
=> Size and position background images in slabs

_sass/molecules/_banner.scss
I've simplified the way banners are structure on codeforamerica.org and I've added support for some color variants. This removes banner elements that are no longer needed--overhead, header etc.--and adds some color styles. This commit also includes a some style tidy-up.
=> Add banner color variants and remove unneeded banner element

_sass/molecules/_alert.scss, _sass/templates/_home.scss, _sass/templates/_primary-page.scss
I'm reworking how alerts work on codeforamerica.org and I want them to have simpler and more-consistent styling across the site. This commit simplifies the alert styles (removing some custom page-specific styling) and introduces a few useful variants, including a few color variants.
=> Consistent, simple alerts with a few variants

_sass/molecules/_card.scss
This styling, which was recently removed, is still being used on the Government Partners page. Let's add it back in for now.
=> Restore index-card styling

_sass/main.scss, _sass/organisms/_card-grid.scss
This adds some simple styling for a card-grid component. The main purpose is to give cards that apprear on the same row, the same height. This styling only applies on wider screens, when cards aren't stacked.
Also sorted the organism imports alphabetically.
=> Add card-grid component

_sass/organisms/_card-grid.scss
There's a large bit of padding at the bottom of cards in the card grid. This evens things out a little.
=> Even out card margins and padding in card-grids

_sass/molecules/_card.scss
To make card image appear more consistent across codeforamerica.org, I'm moving to approach whereby card images are shown as a background images in a `div.card__image` component. 
This commit adds some background-image properties to the `.card__image` subcomponent, makes card iamges have an aspect ratio of 4:3 (by using a padding property hack), and adds a `card__image--contained` variant for when the image should appear smaller and centered (for example, for a logo).
=> Make card images a standard size

_sass/molecules/_slab.scss, _sass/organisms/_global-footer.scss
The margins mean that blocks and their subelement aren't sitting flush with the global-footer. 
I think the way that these margins are set up is overly complicated, so this removes the margins for now.
=> Remove top-margin from global-footer and bottom-margin from last slab

_sass/molecules/_card.scss
A change in the base card element meant that the action cards had a white background. This makes them transparent again.
=> Make action cards transparent

CHANGELOG.md, _sass/molecules/_slab.scss
I accidentally included two declarations for `.gray-bg-slab` and `.red-bg-slab` in the `slab` style sheet. As a result, gray slabs on the website are now way too dark and we only want them to be light gray. 
This fixes the mistake.
=> Remove duplicate slab color variant declarations

CHANGELOG.md, _sass/molecules/_slab.scss
In reverse slabs, we want the headings to be the same color as the rest of the text (white). Let's remove the declaration that makes slab headings black.
=> Let slab headings be the same color as other text in the slab

.travis.yml
Now that codeforamerica.org doesn't hotlink to the style guid anylonger, we can auto deploy the master branch with all the v5 changes.
=> Auto-deploy the master branch of the styleguide
